---
title: "102CHW5"
author: "JING LI"
date: "6/7/2017"
output: pdf_document
---

1
```{r}
probs <- matrix(c(0,1/7,1/7,1/7,1/7,1/7,1/7,1/7,0), nrow=3, byrow = TRUE)
probs

px <- rowSums(probs)
px
py <- colSums(probs)
py

px_y1 <- c(probs[1,1], probs[2,1], probs[3,1]) / sum(probs[,1])
px_y1

px_y2 <- c(probs[1,2], probs[2,2], probs[3,2]) / sum(probs[,2])
px_y2

px_y3 <- c(probs[1,3], probs[2,3], probs[3,3]) / sum(probs[,3])
px_y3

py_x1 = c(probs[1,1], probs[1,2], probs[1,3]) / sum(probs[1,])
py_x1
py_x2 = c(probs[2,1], probs[2,2], probs[2,3]) / sum(probs[2,])
py_x2
py_x3 = c(probs[3,1], probs[3,2], probs[3,3]) / sum(probs[3,])
py_x3


n<-5
jointdist <- array(0,dim=c(3,3,n+1))
jointdist[1,1,1] <- 1
for (t in 2:(n+1)) {
  (x1y1 = px_y1[1]*sum(jointdist[,1,t-1]))
  (x2y1 = px_y1[2]*sum(jointdist[,1,t-1]))
  (x3y1 = px_y1[3]*sum(jointdist[,1,t-1]))
  
  (x1y2 = px_y2[1]*sum(jointdist[,2,t-1]))
  (x2y2 = px_y2[2]*sum(jointdist[,2,t-1]))
  (x3y2 = px_y2[3]*sum(jointdist[,2,t-1]))
  
  (x1y3 = px_y3[1]*sum(jointdist[,3,t-1]))
  (x2y3 = px_y3[2]*sum(jointdist[,3,t-1]))
  (x3y3 = px_y3[3]*sum(jointdist[,3,t-1]))
  
  jointdist[,,t] = matrix(c(x1y1,x1y2,x1y3,x2y1,x2y2,x2y3,x3y1,x3y2,x3y3), nrow = 3,byrow = TRUE)
  
  x1y1 <- py_x1[1] * sum(jointdist[1,,t])
  x1y2 <- py_x1[2] * sum(jointdist[1,,t])
  x1y3 <- py_x1[3] * sum(jointdist[1,,t])
  
  x2y1 <- py_x2[1] * sum(jointdist[2,,t])
  x2y2 <- py_x2[2] * sum(jointdist[2,,t])
  x2y3 <- py_x2[3] * sum(jointdist[2,,t])
  
  x3y1 <- py_x3[1] * sum(jointdist[3,,t])
  x3y2 <- py_x3[2] * sum(jointdist[3,,t])
  x3y3 <- py_x3[3] * sum(jointdist[3,,t])
  
  jointdist[,,t] = matrix(c(x1y1,x1y2,x1y3,x2y1,x2y2,x2y3,x3y1,x3y2,x3y3), nrow = 3,byrow = TRUE)
}

for (t in 0:n) {
  print(paste('joint distribution at t =', t))
  print(jointdist[,,t+1])
}
```
```{r}
2
gibbs <- function(T=1000, M=100, rho=0.9,x0=0,y0=0){
  p <- rep(0,2*M*T)
  dim(p) <- c(2,T,M)
  for (m in 1:M) {
    x <- x0
    y <- y0
    p[,1,m] <- c(x,y)
    for (t in 2:T) {
      x <- rnorm(1, rho*y, sqrt(1-rho^2))
      y <- rnorm(1, rho*x, sqrt(1-rho^2))
      p[,t,m] <- c(x,y)
    }
  }
  p
}

library(animation)
rho <- 0.9
M <- 100
par(mar=c(2,2,1,2),mfrow=c(3,3))
bvn <- gibbs(x0=5,y0=-8,M=M,rho=rho)
lims <- 8*c(-1,1)
for (t in 1:10) {
  plot(bvn[1,t,], bvn[2,t,], xlim = lims, ylim=lims, col=1:M, pch=16, main=paste('t =',t))
  ani.pause(.2)
}
```

